### Get Stoerung
GET http://heizung.rhhome.de:8080/stoerung

### Create Stoerung
POST http://heizung.rhhome.de:8080/stoerung
Content-Type: application/json

{
  "stoerNr": 7
}

### Delete Stoerung
DELETE http://heizung.rhhome.de:8080/stoerung